/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visaotcc;

import controlador.AlunoDao;
import controlador.AlunosPorTurmaDao;
import controlador.PagamentoDao;
import controlador.ResponsaveisDao;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.JTextComponent;
import modelo.Aluno;
import modelo.AlunosPorTurma;
import modelo.Pagamentos;
import modelo.Responsavel;

/**
 *
 * @author Caique
 */
public class AlterarPagamentos extends javax.swing.JFrame {
//     private ArrayList<Integer> id = new ArrayList();
//     private ArrayList<String> Desc = new ArrayList();
    GerenciarPagamentos gerenciarpagamentosForm;
    public AlterarPagamentos alterarpgForm;
    Pagamento PagamentoForm;
    /**
     * Creates new form AlterarPagamentos
     */
    public AlterarPagamentos() {
        initComponents();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/CC.png")).getImage());
        //carregaComboBoxAlunos();
        this.HabilitarCadastrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextFieldDataPagamento = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxMes = new javax.swing.JComboBox<>();
        jTextFieldValorPago = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxFormaPagamento = new javax.swing.JComboBox<>();
        jTextFieldAnoRefencia = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextFieldCodPagamentos = new javax.swing.JTextField();
        jTextFieldTurmasA = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextFieldNomeAluno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Data do Pagamento:");

        try {
            jFormattedTextFieldDataPagamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("Mês referência:");

        jLabel4.setText("Ano referência:");

        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecione --", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));

        jLabel2.setText("Valor Pago:");

        jLabel6.setText("Formas de Pagamento:");

        jComboBoxFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecione --", "Pix", "Crédito", "Débito", "Dinheiro" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldAnoRefencia, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(jTextFieldValorPago))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jFormattedTextFieldDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(330, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAnoRefencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jFormattedTextFieldDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(88, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Alterar Pagamento", jPanel1);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jButton1.setText("Alterar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextFieldCodPagamentos.setEnabled(false);

        jTextFieldTurmasA.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Alterar Pagamentos");

        jTextFieldNomeAluno.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jTextFieldTurmasA, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jTextFieldCodPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155)
                        .addComponent(jButton1)))
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTurmasA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCodPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            
            Double valorpago = Double.valueOf(jTextFieldValorPago.getText().replaceAll(",", "."));
            String datapagamentoText = jFormattedTextFieldDataPagamento.getText();

            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
            java.util.Date datapagamento = dateFormat.parse(datapagamentoText);
            
            String nomealuno = jTextFieldNomeAluno.getText();
            String mesderefenencia = (String) jComboBoxMes.getSelectedItem();
            Integer anoreferencia = Integer.parseInt(jTextFieldAnoRefencia.getText());
            String turmadoaluno = jTextFieldTurmasA.getText();
            String formapagamento = (String) jComboBoxFormaPagamento.getSelectedItem();
            Integer id = Integer.parseInt(jTextFieldCodPagamentos.getText());      
            
            Pagamentos u = new Pagamentos(valorpago, datapagamento, mesderefenencia, anoreferencia, turmadoaluno, formapagamento, nomealuno, id, null);
            
            

            PagamentoDao dao = new PagamentoDao();
            dao.atualizar(u);
            gerenciarpagamentosForm.callback();

            JOptionPane.showMessageDialog(this, "Registro atualizado.");
            dispose();
        } catch (ParseException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed
//private void carregaComboBoxAlunos() {
//    try {
//        AlunosPorTurmaDao dao = new AlunosPorTurmaDao();
//        List<AlunosPorTurma> lista = dao.buscar("");
//
//        this.id.add(0);
//        this.Desc.add("-- Selecione --");
//
//        Map<String, List<Integer>> alunosMap = new HashMap<>();
//        Map<String, Integer> contadorPorAluno = new HashMap<>();
//
//        for (AlunosPorTurma alunoTurma : lista) {
//            int idAlunosPorTurma = alunoTurma.getId();
//            int idAluno = alunoTurma.getIdaluno();
//
//            AlunoDao alunoDao = new AlunoDao();
//            Aluno aluno = alunoDao.buscarPorId(idAluno);
//
//            if (aluno != null) {
//                String nomeAluno = aluno.getNome();
//
//                if (alunosMap.containsKey(nomeAluno)) {
//                    alunosMap.get(nomeAluno).add(idAlunosPorTurma);
//                } else {
//                    List<Integer> ids = new ArrayList<>();
//                    ids.add(idAlunosPorTurma);
//                    alunosMap.put(nomeAluno, ids);
//                    contadorPorAluno.put(nomeAluno, 0);
//                }
//            }
//        }
//
//        for (Map.Entry<String, List<Integer>> entry : alunosMap.entrySet()) {
//            String nomeAluno = entry.getKey();
//            List<Integer> ids = entry.getValue();
//            int contador = contadorPorAluno.get(nomeAluno);
//
//            for (int id : ids) {
//                this.id.add(id);
//                if (contador > 0) {
//                    this.Desc.add(nomeAluno + " " + contador);
//                } else {
//                    this.Desc.add(nomeAluno);
//                }
//                contador++;
//            }
//
//            contadorPorAluno.put(nomeAluno, contador);
//        }
//
//        jComboBoxAlunos.setModel(new javax.swing.DefaultComboBoxModel<>(Desc.toArray(new String[0])));
//        
//        
//
//    } catch (Exception ex) {
//        ex.printStackTrace();
//        JOptionPane.showMessageDialog(this, "Erro ao carregar combobox de alunos: " + ex);
//    }
//}   
   public void HabilitarCadastrar() {
    jButton1.setEnabled(false); // Começa desativado

    // Crie um DocumentListener para monitorar os campos de texto
    DocumentListener documentListener = new DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) {
            checkFields();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            checkFields();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            checkFields();
        }
    };

    // Adicione o DocumentListener aos campos relevantes
    jTextFieldAnoRefencia.getDocument().addDocumentListener(documentListener);
    jTextFieldValorPago.getDocument().addDocumentListener(documentListener);
    jFormattedTextFieldDataPagamento.getDocument().addDocumentListener(documentListener);

    // Adicione um ActionListener para monitorar as ComboBoxes
    ActionListener comboBoxListener = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            checkFields(); // Quando as ComboBoxes forem alteradas, chame checkFields() para atualizar a habilitação do botão
        }
    };
    jComboBoxFormaPagamento.addActionListener(comboBoxListener);
    jComboBoxMes.addActionListener(comboBoxListener);

    // Verifique os campos uma vez para garantir que o botão esteja corretamente habilitado ou desabilitado inicialmente
    checkFields();
}
public void checkFields() {
    String ano = jTextFieldAnoRefencia.getText();
    String valor = jTextFieldValorPago.getText();
    String data = jFormattedTextFieldDataPagamento.getText();

    // Verifique se algum dos campos obrigatórios está vazio ou inválido
    if (ano.isEmpty() || data.equals("    -  -  ") || valor.isEmpty()) {
        jButton1.setEnabled(false);
        return;
    }

    try {
        int ano2 = Integer.parseInt(ano);

        // Verifique a validade da data
        boolean dateValid = data.matches("\\d{2}-\\d{2}-\\d{4}");
        // Verifique se a data está completamente preenchida (10 caracteres)
        if (dateValid && data.length() == 10) {
            // Tente converter o valor para double
            double valor2 = Double.parseDouble(valor.replace(",", "."));

            // Verifique se os campos não são iguais a zero e se os campos adicionais estão preenchidos corretamente
            jButton1.setEnabled(jComboBoxFormaPagamento.getSelectedIndex() != 0 && jComboBoxMes.getSelectedIndex() != 0);
        } else {
            jButton1.setEnabled(false);
        }
    } catch (NumberFormatException e) {
        // Em caso de erro na conversão, desative o botão
        jButton1.setEnabled(false);
    }
}




    public void mostrarPagamentos(String idTexto){
    try {
        Integer id = Integer.parseInt(idTexto);
        
        PagamentoDao dao = new PagamentoDao();
        Pagamentos obj = dao.getPagamentos(id);
        
        if (obj != null) {
            // Formatar a data para exibição no formato desejado
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
            String dataPagamentoFormatada = dateFormat.format(obj.getDatapagamento());
            
            // Preenche os dados do formulário
            jTextFieldValorPago.setText(obj.getValorpago().toString());
            jFormattedTextFieldDataPagamento.setText(dataPagamentoFormatada); // Exibe a data formatada
            jTextFieldAnoRefencia.setText(obj.getAnoreferencia().toString());
            jTextFieldCodPagamentos.setText(obj.getId().toString());
            jTextFieldTurmasA.setText(obj.getTurmadoaluno());
            jTextFieldNomeAluno.setText(obj.getNomealuno());
           // Adicione os itens aos ComboBoxes
            jComboBoxMes.setSelectedItem(obj.getMesderefenencia());
            jComboBoxFormaPagamento.setSelectedItem(obj.getFormapagamento());
            
        } else {
            JOptionPane.showMessageDialog(this, "Registro não encontrado");
            jTextFieldValorPago.setText("");
            jFormattedTextFieldDataPagamento.setText("    -  -  ");
            jTextFieldAnoRefencia.setText("");
            jTextFieldCodPagamentos.setText("");
            jTextFieldTurmasA.setText("");
            jComboBoxMes.setToolTipText("-- Selecione --");
            jComboBoxFormaPagamento.setToolTipText("-- Selecione --");
            //jTextFieldIDAluno.requestFocus();
        }
        
    } catch(Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erro ao consultar registro");
            jTextFieldValorPago.setText("");
            jFormattedTextFieldDataPagamento.setText("    -  -  ");
            jTextFieldAnoRefencia.setText("");
            jTextFieldCodPagamentos.setText("");
            jTextFieldTurmasA.setText("");
            jComboBoxMes.setToolTipText("-- Selecione --");
            jComboBoxFormaPagamento.setToolTipText("-- Selecione --");
            jTextFieldAnoRefencia.setText(null);
    }
}

  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarPagamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxFormaPagamento;
    private javax.swing.JComboBox<String> jComboBoxMes;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataPagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldAnoRefencia;
    private javax.swing.JTextField jTextFieldCodPagamentos;
    private javax.swing.JTextField jTextFieldNomeAluno;
    private javax.swing.JTextField jTextFieldTurmasA;
    private javax.swing.JTextField jTextFieldValorPago;
    // End of variables declaration//GEN-END:variables
}
