/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visaotcc;

import Login.DadosDeSessao;
import controlador.AlunoDao;
import controlador.ResponsaveisDao;
import controlador.ResponsavelPorAlunoDao;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Aluno;
import modelo.Responsavel;
import modelo.ResponsavelPorAluno;

/**
 *
 * @author Caique
 */
public class Alunos_Responsaveis extends javax.swing.JFrame {
     private ArrayList<Integer> idAluno = new ArrayList();
     private ArrayList<String> DescAluno = new ArrayList();
     
     private ArrayList<Integer> idAluno1 = new ArrayList();
     private ArrayList<String> DescAluno1 = new ArrayList();
     
     private ArrayList<Integer> idResp = new ArrayList();
     private ArrayList<String> DescResp = new ArrayList();
     
     private ArrayList<Integer> idResp1 = new ArrayList();
     private ArrayList<String> DescResp1 = new ArrayList();
    /**
     * Creates new form Alunos_Responsaveis
     */
    public Alunos_Responsaveis() {
        initComponents();
        this.setTitle(DadosDeSessao.nomeSistema);
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/CC.png")).getImage());
        carregaComboBoxAluno();
        carregaComboBoxAluno1();
        carregaComboBoxResponsavel();
        carregaComboBoxResponsavel1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxAluno = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxResponsavel = new javax.swing.JComboBox<>();
        jTextFieldIDAluno = new javax.swing.JTextField();
        jTextFieldIDResponsavel = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxAluno1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxResponsavel1 = new javax.swing.JComboBox<>();
        jTextFieldIDAluno1 = new javax.swing.JTextField();
        jTextFieldIDResponsavel1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Aluno:");

        jComboBoxAluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecione --" }));
        jComboBoxAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAlunoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Responsável:");

        jComboBoxResponsavel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecione --" }));
        jComboBoxResponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxResponsavelActionPerformed(evt);
            }
        });

        jTextFieldIDAluno.setEnabled(false);

        jTextFieldIDResponsavel.setEnabled(false);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 186, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextFieldIDAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jTextFieldIDResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIDAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIDResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Gerenciar", jPanel1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Aluno:");

        jComboBoxAluno1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecione --" }));
        jComboBoxAluno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAluno1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Responsável:");

        jComboBoxResponsavel1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecione --" }));
        jComboBoxResponsavel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxResponsavel1ActionPerformed(evt);
            }
        });

        jTextFieldIDAluno1.setEnabled(false);

        jTextFieldIDResponsavel1.setEnabled(false);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Remover");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxAluno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxResponsavel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextFieldIDAluno1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jTextFieldIDResponsavel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 186, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxAluno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxResponsavel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIDAluno1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIDResponsavel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Remover", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Vincular/Remover Aluno a Responsável");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAlunoActionPerformed
         String nomeAluno = (String) jComboBoxAluno.getSelectedItem();

        if (nomeAluno != null && !nomeAluno.isEmpty()) {
            try {
                AlunoDao dao = new AlunoDao();
                Integer idAluno = dao.obterIdAlunoPeloNome(nomeAluno);

                jTextFieldIDAluno.setText(String.valueOf(idAluno));
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao obter o ID do aluno.");
            }
          }        
    }//GEN-LAST:event_jComboBoxAlunoActionPerformed

    private void jComboBoxResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxResponsavelActionPerformed
            String nomeResp = (String) jComboBoxResponsavel.getSelectedItem();

        if (nomeResp != null && !nomeResp.isEmpty()) {
            try {
                ResponsaveisDao dao = new ResponsaveisDao();
                Integer idResp = dao.obterIdRespPeloNome(nomeResp);

                jTextFieldIDResponsavel.setText(String.valueOf(idResp)); // Corrigido para idResp
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao obter o ID do responsavel.");
            }
          }          
    }//GEN-LAST:event_jComboBoxResponsavelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         int idAluno = Integer.parseInt(jTextFieldIDAluno.getText());
         int idResponsavel = Integer.parseInt(jTextFieldIDResponsavel.getText());
    
        ResponsavelPorAlunoDao respdao = new ResponsavelPorAlunoDao();
        try {
            respdao.inserir(idAluno, idResponsavel);
            JOptionPane.showMessageDialog(this, "Registro inserido.");
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
            // Lidar com a exceção
         }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxAluno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAluno1ActionPerformed
        String nomeAluno = (String) jComboBoxAluno1.getSelectedItem();

        if (nomeAluno != null && !nomeAluno.isEmpty()) {
            try {
                AlunoDao dao = new AlunoDao();
                Integer idAluno = dao.obterIdAlunoPeloNome(nomeAluno);

                jTextFieldIDAluno1.setText(String.valueOf(idAluno));
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao obter o ID do aluno.");
            }
          }        
    }//GEN-LAST:event_jComboBoxAluno1ActionPerformed

    private void jComboBoxResponsavel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxResponsavel1ActionPerformed
        String nomeResp = (String) jComboBoxResponsavel1.getSelectedItem();

        if (nomeResp != null && !nomeResp.isEmpty()) {
            try {
                ResponsaveisDao dao = new ResponsaveisDao();
                Integer idResp = dao.obterIdRespPeloNome(nomeResp);

                jTextFieldIDResponsavel1.setText(String.valueOf(idResp)); // Corrigido para idResp
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao obter o ID do responsavel.");
            }
          }          
    }//GEN-LAST:event_jComboBoxResponsavel1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String idaluno = jTextFieldIDAluno1.getText();
       String idresponsavel = jTextFieldIDResponsavel1.getText();

        if (!idaluno.isEmpty() && !idresponsavel.isEmpty()) {
            try {
                Integer idresponsavel1 = Integer.parseInt(idresponsavel);
                Integer idaluno1 = Integer.parseInt(idaluno);

                ResponsavelPorAluno u = new ResponsavelPorAluno(idaluno1, idresponsavel1);

                ResponsavelPorAlunoDao alunoDao = new ResponsavelPorAlunoDao();
                alunoDao.removerAlunoDoResponsavel(idaluno1, idresponsavel1); 

                JOptionPane.showMessageDialog(this, "Aluno desvinculado ao responsavel.");
                this.dispose();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Por favor, insira valores numéricos válidos para ID do responsavel e ID do aluno.");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, preencha os campos ID da turma e ID do aluno.");
        }        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed
    private void carregaComboBoxAluno(){
                try{
                    AlunoDao dao = new AlunoDao();
                    List<Aluno> lista = dao.buscar("");

                    //Atribui o primeiro grupo(0 - selecione)
                    this.idAluno.add(0);
                    this.DescAluno.add("-- Selecione --");

                    //Atribui os grupos que estão cadastrados no banco
                    for(Aluno aluno : lista){
                        this.idAluno.add(aluno.getId());
                        this.DescAluno.add(aluno.getNome());
                    }

                    //Carrega no combobox a lista de grupos 
                    jComboBoxAluno.setModel(new javax.swing.DefaultComboBoxModel<>(DescAluno.toArray(new String[0])));
                }catch(Exception ex){
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Erro ao carregar combobox 'grupo de usuario': "+ex);
                }
    }
    private void carregaComboBoxAluno1(){
                try{
                    AlunoDao dao = new AlunoDao();
                    List<Aluno> lista = dao.buscar("");

                    //Atribui o primeiro grupo(0 - selecione)
                    this.idAluno1.add(0);
                    this.DescAluno1.add("-- Selecione --");

                    //Atribui os grupos que estão cadastrados no banco
                    for(Aluno aluno : lista){
                        this.idAluno1.add(aluno.getId());
                        this.DescAluno1.add(aluno.getNome());
                    }

                    //Carrega no combobox a lista de grupos 
                    jComboBoxAluno1.setModel(new javax.swing.DefaultComboBoxModel<>(DescAluno1.toArray(new String[0])));
                }catch(Exception ex){
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Erro ao carregar combobox 'grupo de usuario': "+ex);
                }
    }
    private void carregaComboBoxResponsavel(){
                try{
                    ResponsaveisDao dao = new ResponsaveisDao();
                    List<Responsavel> lista = dao.buscar("");

                    //Atribui o primeiro grupo(0 - selecione)
                    this.idResp.add(0);
                    this.DescResp.add("-- Selecione --");

                    //Atribui os grupos que estão cadastrados no banco
                    for(Responsavel resp : lista){
                        this.idResp.add(resp.getId());
                        this.DescResp.add(resp.getNome());
                    }

                    //Carrega no combobox a lista de grupos 
                    jComboBoxResponsavel.setModel(new javax.swing.DefaultComboBoxModel<>(DescResp.toArray(new String[0])));
                }catch(Exception ex){
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Erro ao carregar combobox 'grupo de usuario': "+ex);
                }
    }
    
    private void carregaComboBoxResponsavel1(){
                try{
                    ResponsaveisDao dao = new ResponsaveisDao();
                    List<Responsavel> lista = dao.buscar("");

                    //Atribui o primeiro grupo(0 - selecione)
                    this.idResp1.add(0);
                    this.DescResp1.add("-- Selecione --");

                    //Atribui os grupos que estão cadastrados no banco
                    for(Responsavel resp : lista){
                        this.idResp1.add(resp.getId());
                        this.DescResp1.add(resp.getNome());
                    }

                    //Carrega no combobox a lista de grupos 
                    jComboBoxResponsavel1.setModel(new javax.swing.DefaultComboBoxModel<>(DescResp1.toArray(new String[0])));
                }catch(Exception ex){
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Erro ao carregar combobox 'grupo de usuario': "+ex);
                }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alunos_Responsaveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alunos_Responsaveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alunos_Responsaveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alunos_Responsaveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alunos_Responsaveis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxAluno;
    private javax.swing.JComboBox<String> jComboBoxAluno1;
    private javax.swing.JComboBox<String> jComboBoxResponsavel;
    private javax.swing.JComboBox<String> jComboBoxResponsavel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldIDAluno;
    private javax.swing.JTextField jTextFieldIDAluno1;
    private javax.swing.JTextField jTextFieldIDResponsavel;
    private javax.swing.JTextField jTextFieldIDResponsavel1;
    // End of variables declaration//GEN-END:variables
}
